FlaskApp/StarWars/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

class PostForm(FlaskForm):
    title =StringField('Title', validators=[DataRequired(), Length(min= 10, max = 120)])
    content = TextAreaField('Content', validators= [DataRequired()])
    submit = SubmitField('Post')

FlaskApp/StarWars/main/routes.py
from flask import request, render_template, Blueprint
from StarWars.Models import Article


main = Blueprint('main', __name__)

@main.route("/")
def homePage():
    page = request.args.get('page', 1 , type = int)
    posts = Article.query.order_by(Article.create_date.desc()).paginate(page = page, per_page = 3)
    return render_template("index.html", posts = posts)

@main.route("/aboutUs")
def aboutPage():
    return render_template("about.html", title = "About")

FlaskApp/StarWars/posts/routes.py
from flask import request, render_template, redirect, flash, url_for, abort, Blueprint
from flask_login import current_user, login_required
from StarWars import db
from StarWars.Models import Article
from StarWars.posts.forms import PostForm




posts = Blueprint('posts', __name__)

@posts.route("/New Post", methods=['GET', 'POST'])
@login_required
def PostPage():
    form = PostForm()
    if form.validate_on_submit():
        post = Article(title = form.title.data, content = form.content.data, author = current_user )
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.homePage'))
    return render_template('post.html', form = form, title = 'New Post', legend = 'Create Post')

@posts.route("/Post/<int:post_id>")
def View_Post(post_id):
    post = Article.query.get_or_404(post_id)
    return render_template("ViewPost.html", title = post.title, post = post)


@posts.route("/Post/<int:post_id>/update", methods = ['GET', 'POST'])
@login_required
def Update_Post(post_id):
    post = Article.query.get_or_404(post_id)
    if post.author == current_user:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            db.session.commit()
            flash("Your post has been updated!", 'success')
            return redirect(url_for('posts.View_Post', post_id = post.id))
        elif request.method == "GET":
            form.title.data = post.title
            form.content.data = post.content
        return render_template("post.html", post = post, form = form, title = 'Update Post', legend = "Update Post")
    else:
        abort(403)
       

@posts.route("/Post/<int:post_id>/delete", methods = ["GET", "POST"])
@login_required
def Delete_Post(post_id):
    post = Article.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', "success")
    return redirect(url_for('main.homePage'))

FlaskApp/StarWars/users/routes.py
from flask import request, render_template, redirect, flash, url_for, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from StarWars import db, bcrypt
from StarWars.users.forms import RegisterationForm, LoginForm, UpdateForm, RequestResetForm, ResetPasswordForm
from StarWars.Models import User, Article
from StarWars.users.utils import save_picture, send_reset_email



users = Blueprint('users', __name__)

@users.route("/register", methods = ['GET', 'POST'])
def registerpage():
    if current_user.is_authenticated:
        return redirect(url_for('main.homePage'))
    form = RegisterationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(fullname = form.fullname.data, 
                    username=form.username.data, 
                    email = form.email.data,
                    password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your Account was successfully created and you can now login!', "success")
        return redirect(url_for("users.loginpage"))
    return render_template("register.html", title = "Register", form = form)

@users.route("/login", methods = ['GET', 'POST'])
def loginpage():
    if current_user.is_authenticated:
        return redirect(url_for('main.homePage'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            flash("You are now logged in!", 'success')
            return redirect(next_page) if next_page else redirect( url_for("main.homePage"))
        else:
            flash("Invalid Login. Confirm email and password", 'danger' )
    return render_template("login.html", title = "Login", form = form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect( url_for("main.homePage"))



@users.route("/dashboard", methods = ['GET', 'POST'])
@login_required
def dashboardPage():
    form = UpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            user_pic = save_picture(form.picture.data)
            current_user.prof_pic = user_pic
        current_user.fullname = form.fullname.data
        current_user.email = form.email.data
        current_user.username = form.username.data
        db.session.commit()
        flash("Your account info has been updated", 'success')
        return redirect(url_for('users.dashboardPage'))
    elif request.method == 'GET':
        form.fullname.data = current_user.fullname
        form.username.data = current_user.username
        form.email.data = current_user.email
    user_img = "static/images/profile_pic/" + current_user.prof_pic
    return render_template('dashboard.html', title = "Dashboard", user_img = user_img, form = form)




@users.route('/user/<string:username>')
def User_Posts(username):
    page = request.args.get('page', 1, type = int)
    user = User.query.filter_by(username = username).first_or_404()
    posts = Article.query\
    .filter_by(author = user)\
    .order_by(Article.create_date.desc())\
    .paginate(per_page = 3, page = page)
    return render_template('userPosts.html', posts = posts, user = user)


@users.route('/reset_password', methods = ['GET', 'POST'])
def Reset_Request():
    if current_user.is_authenticated:
        return redirect(url_for('main.homePage'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent to the email provided with instructions on how to reset your password", 'info')
        return redirect(url_for('users.loginpage'))
    return render_template('resetRequest.html', title = "Reset Password", form = form)


@users.route('/reset_password/<token>', methods = ['GET', 'POST'])
def Reset_Password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.homePage'))
    user = User.verify_reset_token(token)
    if user is None:
        flash("Invalid or expired reset password token", 'warning')
        return redirect(url_for('users.Reset_Request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been successively updated, you can now login with your new password!', "success")
        return redirect(url_for("users.loginpage"))
    return render_template('resetPassword.html', form = form, title = "Reset Password")

FlaskApp/StarWars/templates/ViewPost.html
{% extends 'layout.html' %}

{% block Body1 %}
<div class="blog-posts">
    <div class="blog-post">
        
        <input type="checkbox" name="" id="" class="img-check">
        <div class="profile-pic-holder">
            <img src="{{ url_for('static', filename = 'images/profile_pic/' + post.author.prof_pic) }}" alt="">
        </div>

        <div class="profile">
            <div class="profile-info">
                <a href="">{{ post.author.username }}</a>
                <p>{{ post.create_date.strftime('%Y-%m-%d') }}</p> 
            </div>
            {% if post.author == current_user %}
                <div>
                    <a href="{{ url_for('posts.Update_Post', post_id = post.id) }}" class = 'button-close' style="color: white;">Update</a>
                    <button class="button-danger" onclick="document.getElementById('deleteModal').style.display='block';
                    document.getElementById('main-header').style.pointerEvents='none';">Delete</button>
                </div>
            {% endif %}
        </div>
        
        
        <div class="post-body">
            <hr>
            <h2>{{ post.title }}</h2>
            <p>{{ post.content }}</p>
        </div>

        <div class="picture-display">
            
            <img src="{{ url_for('static', filename = 'images/profile_pic/' + post.author.prof_pic) }}" alt="">
        </div>
    </div>
   
</div>
<div id="deleteModal" class="modal fade", Toggle = "stress">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post ?</h5>
                <button class="modal-dismiss" onclick="document.getElementById('deleteModal').style.display='none';
                document.getElementById('main-header').style.pointerEvents='auto';"><span>&times;</span></button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <form action="{{ url_for('posts.Delete_Post', post_id = post.id) }}" method="post">
                    <input class="button-danger" type="submit" value="Delete">
                </form>
                <button class="button-close" onclick="document.getElementById('deleteModal').style.display='none';
                document.getElementById('main-header').style.pointerEvents='auto';">close</button>
            </div>
        </div>
    </div>

</div>

{% endblock Body1 %}

FlaskApp/StarWars/templates/about.html
{% extends "layout.html" %}

{% block Body %}

{% endblock Body %}

FlaskApp/StarWars/templates/dashboard.html
{% extends 'layout.html' %}

{% block Body1 %}
{% from "includes/_formhelpers.html" import render_field %}
    <div class="content-hx">
        <div class="dashboard-content">
            <div class="dashboard-profile">
                <img src="{{ user_img }}" alt="">
                <div class="profile-info">
                    <h1>{{ current_user.fullname }}</h1>
                    <small>{{ current_user.email }}</small>
                </div>
                
            </div>
            <div class="form-holder">
                <form action="" method="post" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend>Account Info</legend>
                        <div class="form-group">
                            {{ form.fullname.label(class = "form-control-label") }}
                            {{ render_field(form.fullname) }}
                        </div>
                        <div class="form-group">
                            {{ form.username.label(class = "form-control-label") }}
                            {{ render_field(form.username) }}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class = "form-control-label") }}
                            {{ render_field(form.email) }}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.picture.label(class = "form-control-label") }}
                        {{ form.picture(class = 'form-control-file') }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <div class="inline-help">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class = "form-control btn") }}
                    </div>
                </form>
            </div>
        </div>
        
    </div>
 
{% endblock Body1 %}

FlaskApp/StarWars/templates/index.html
{% extends 'layout.html' %}

{% block Body %}
<div class="blog-posts">
    {% for post in posts.items %}
        <div class="blog-post">
            
            <input type="checkbox" name="" id="" class="img-check">
            <div class="profile-pic-holder">
                <img src="{{ url_for('static', filename = 'images/profile_pic/' + post.author.prof_pic) }}" alt="">
            </div>

            <div class="profile">
                <div class="profile-info">
                    <a href="{{ url_for('users.User_Posts', username = post.author.username) }}">{{ post.author.username }}</a>
                    <p>{{ post.create_date.strftime('%Y-%m-%d') }}</p> 
                </div>
                
            </div>
            
            <div class="post-body">
                <hr>
                <h2><a href="{{ url_for('posts.View_Post', post_id = post.id) }}">{{ post.title }}</a></h2>
                <p>{{ post.content }}</p>
            </div>

            <div class="picture-display">
                
                <img src="{{ url_for('static', filename = 'images/profile_pic/' + post.author.prof_pic) }}" alt="">
            </div>
        </div>
    {% endfor %}
   
</div>





{% endblock Body %}

{% block more %}
    <div class="after-post">
        {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 2, right_current = 3) %}
            {% if page_num %}
                {% if page_num == posts.page %}
                    <a class="btn-info solid" href="{{ url_for('main.homePage', page = page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn-info" href="{{ url_for('main.homePage', page = page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}

        {% endfor %}
    </div>

    

{% endblock more %}

FlaskApp/StarWars/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'modal.css') }}">
    <script type="application/javascript" src="{{ url_for('static', filename = 'fontawesome/js/all.js') }}"></script>
    {% if title %}
        <title>StarWars - {{ title }}</title>
    {% else %}
        <title>StarWars</title>
    {% endif %}
</head>
<body>
    <header id="main-header">
        
        <nav>
            <input type="checkbox" name="" id="check">
            <div class="logo-holder">
                <h1 class="logo"><a href="{{ url_for('main.homePage') }}">Star<span>Wars</span></a></h1>
            </div>
            <div class="nav-btn">
                <div class="nav-links">
                    <ul>
                        <li class="nav-link" style="--i: .6s"><a href="{{ url_for('main.homePage') }}">Home</a></li>
                        <li class="nav-link" style="--i: .8s"><a href="{{ url_for('main.aboutPage') }}">About</a></li>
                        <li class="nav-link" style="--i: 1s">
                            <a href="">Services<i class="fas fa-caret-down"></i></a>
                            <div class="dropdown">
                                <ul>
                                    <li class="dropdown-link">
                                        <a href="">Geology <i class="fas fa-caret-down"></i></a>
                                        <div class="dropdown second">
                                            <ul>
                                                <li class="dropdown-link"><a href="">Physical</a></li>
                                                <li class="dropdown-link"><a href="">Stratigraphy</a></li>
                                                <li class="dropdown-link"><a href="">GeoChemistry</a></li>
                                                <li class="dropdown-link"><a href="">Hydrogeology</a></li>
                                                <li class="dropdown-link"><a href="">EngGeology</a></li>
                                                <div class="arrow"></div>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="dropdown-link">
                                        <a href="">Geophysics <i class="fas fa-caret-down"></i></a>
                                        <div class="dropdown second">
                                            <ul>
                                                <li class="dropdown-link"><a href="">Seismic</a></li>
                                                <li class="dropdown-link"><a href="">Electrical</a></li>
                                                <li class="dropdown-link"><a href="">Electromagnetic</a></li>
                                                <li class="dropdown-link"><a href="">Gravity</a></li>
                                                <li class="dropdown-link"><a href="">Magnetic</a></li>
                                                <div class="arrow"></div>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="dropdown-link"><a href="">Maps</a></li>
                                    <li class="dropdown-link"><a href="">Seminar</a></li>
                                    <div class="arrow"></div>
                                </ul>
    
                            </div>
                        </li>
                        <li class="nav-link" style="--i: 1.2s">
                            <a href="">Contact<i class="fas fa-caret-down"></i></a>
                            <div class="dropdown">
                                <ul>
                                    <li class="dropdown-link"><a href="">Email</a></li>
                                    <li class="dropdown-link"><a href="">Phone</a></li>
                                    <li class="dropdown-link"><a href="">FaceBook</a></li>
                                    <li class="dropdown-link"><a href="">Instagram</a></li>
                                    <li class="dropdown-link"><a href="">Twitter</a></li>
                                    <li class="dropdown-link"><a href="">CustomerCare</a></li>
                                    <div class="arrow"></div>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="log-sign" style="--i: 1.5s">
                    {% if current_user.is_authenticated %}
                        <a class="btn solid" href="{{ url_for('posts.PostPage') }}">NewPost</a>
                        <a class="btn solid" href="{{ url_for('users.dashboardPage') }}">Dashboard</a>
                        <a class="btn transparent" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="btn solid" href="{{ url_for('users.loginpage') }}">Login</a>
                        <a class="btn transparent" href="{{ url_for('users.registerpage') }}">Register</a>
                    {% endif %}
                </div>
            </div>
            <div class="hamburger-container">
                <div class="hamburger-menu">
                    <div></div>
                </div>
            </div>
            
        </nav>
    </header>
    <main>
        <section>
            <div class="overlay">
                
            </div>
            <div class="container-main">
                {% include 'includes/_messages.html' %}
                {% block info_top %} {% endblock info_top %}
                {% if title %}
                    <div  class="container-alt">
                    
                        {% block Body1 %}
        
                        {% endblock %} 
                        <div class="side-bar-container">
                            <div class="side-bar">
                                <h2>Quick Links</h2>
                                <p>Travel at the speed of light, click on any of the link below:</p>
                                <ul class="side-links">
                                    <li class="side-link"><a href="">Latest Post</a></li>
                                    <li class="side-link"><a href="">Latest Gist</a></li>
                                    <li class="side-link"><a href="">Anouncement</a></li>
                                    <li class="side-link"><a href="">Light News</a></li>
                                </ul>
                                
                            </div>
                        </div>    
                    </div>
                {% else %}
                    <div  class="container">
                    
                        {% block Body %}
        
                        {% endblock %} 
                        <div class="side-bar-container">
                            <div class="side-bar">
                                <h2>Quick Links</h2>
                                <p>Travel at the speed of light, click on any of the link below:</p>
                                <ul class="side-links">
                                    <li class="side-link"><a href="">Latest Post</a></li>
                                    <li class="side-link"><a href="">Latest Gist</a></li>
                                    <li class="side-link"><a href="">Anouncement</a></li>
                                    <li class="side-link"><a href="">Light News</a></li>
                                </ul>
                                
                            </div>
                        </div>    
                    </div>
                    {% block more %}
                    
                    {% endblock more %}
                {% endif %}
                
            </div>           
            

            
        </section>
    </main>
    <script type="application/javascript">
        var modal = document.getElementById('deleteModal');
        window.addEventListener('click', modalclose);

        function modalclose(event){
            if(event.target == modal){
                modal.style.display = 'none';
            };
        }

        
    </script>
</body>
</html>

FlaskApp/StarWars/templates/login.html
{% extends "layout.html" %}

{% block Body1 %}
{% from "includes/_formhelpers.html" import render_field %}
<div class="content-hx">
    <div class="form-holder">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend>Sign In</legend>
                <div class="form-group">
                    {{ form.email.label(class = "form-control-label") }}
                    {{ render_field(form.email) }}
                </div>
                <div class="form-group">
                    {{ form.password.label(class = "form-control-label") }}
                    {{ render_field(form.password) }}
                </div> 
                <div class="form-check">
                    {{ form.remember(class = "form-check-input") }}
                    {{ form.remember.label(class = "form-check-label") }}
                </div>   
            </fieldset>
            <div class="form-group">
                {{ form.submit(class = "form-control btn") }}
            </div>
            <small class="text-muted">
                <a href="{{ url_for('users.Reset_Request') }}" class="plane-btn">forgot password?</a>
            </small>
        </form>
    </div>
    <div class="bottom-info">
        <small class="text-muted">
            Don't Have Existing Account? <a class="plane-btn" href="{{ url_for('users.registerpage') }}">Sign Up Now</a>
        </small>
    </div>
</div>



{% endblock Body1 %}

FlaskApp/StarWars/templates/post.html
{% extends 'layout.html' %}

{% block Body1 %}
{% from 'includes/_formhelpers.html' import render_field %}
    <div class="content-hx">
        <div class="form-holder">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend>{{ legend }}</legend>
                    
                    <div class="form-group">
                        {{ form.title.label(class = 'form-control-label') }}
                        {{ render_field(form.title) }}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class = 'form-control-label') }}
                        {{ render_field(form.content) }}
                    </div>

                </fieldset>
                {{ form.submit(class = 'form-control btn') }}
            </form>

        </div>

    </div>

{% endblock Body1 %}

FlaskApp/StarWars/templates/register.html
{% extends "layout.html" %}

{% block Body1 %}
{% from "includes/_formhelpers.html" import render_field %}
<div class="content-hx">
    <div class="form-holder">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend>Join Today</legend>
                <div class="form-group">
                    {{ form.fullname.label(class = "form-control-label") }}
                    {{ render_field(form.fullname) }}
                </div>
                <div class="form-group">
                    {{ form.username.label(class = "form-control-label") }}
                    {{ render_field(form.username) }}
                </div>
                <div class="form-group">
                    {{ form.email.label(class = "form-control-label") }}
                    {{ render_field(form.email) }}
                </div>
                <div class="form-group">
                    {{ form.password.label(class = "form-control-label") }}
                    {{ render_field(form.password) }}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class = "form-control-label") }}
                    {{ render_field(form.confirm_password) }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class = "form-control btn") }}
            </div>
        </form>
    </div>
    
    <div class="bottom-info">
        <small class="text-muted">
            Already Have an Account? <a class="plane-btn" href="{{ url_for('users.loginpage') }}">Sign In</a>
        </small>
    </div>
</div>



{% endblock Body1 %}

FlaskApp/StarWars/templates/resetPassword.html
{% extends 'layout.html' %}

{% block Body1 %}
{% from 'includes/_formhelpers.html' import render_field %}
    <div class="content-hx">
        <div class="form-holder">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend>Reset Password</legend>
                    <div class="form-group">
                        {{ form.password.label(class= 'form-control-label') }}
                        {{ render_field(form.password) }}
                    </div>
                    <div class="form-group">
                        {{ form.confirm_password.label(class= 'form-control-label') }}
                        {{ render_field(form.confirm_password) }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class = "form-control btn") }}
                </div>
            </form>
        </div>
    </div>

{% endblock Body1 %}

FlaskApp/StarWars/templates/resetRequest.html
{% extends 'layout.html' %}

{% block Body1 %}
{% from 'includes/_formhelpers.html' import render_field %}
    <div class="content-hx">
        <div class="form-holder">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend>Reset Password</legend>
                    <div class="form-group">
                        {{ form.email.label(class = 'form-control-label') }}
                        {{ render_field(form.email) }}
                    </div>
                    
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class = "form-control btn") }}
                </div>
            </form>
        </div>
    </div>


{% endblock Body1 %}

FlaskApp/StarWars/templates/userPosts.html
{% extends 'layout.html' %}


{% block Body %}

<div class="blog-posts">
    <h1 class="info-top">Posts by <span>{{ user.username }}</span>  ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <div class="blog-post">
            
            <input type="checkbox" name="" id="" class="img-check">
            <div class="profile-pic-holder">
                <img src="{{ url_for('static', filename = 'images/profile_pic/' + post.author.prof_pic) }}" alt="">
            </div>

            <div class="profile">
                <div class="profile-info">
                    <a href="">{{ post.author.username }}</a>
                    <p>{{ post.create_date.strftime('%Y-%m-%d') }}</p> 
                </div>
                
            </div>
            
            <div class="post-body">
                <hr>
                <h2><a href="{{ url_for('posts.View_Post', post_id = post.id) }}">{{ post.title }}</a></h2>
                <p>{{ post.content }}</p>
            </div>

            <div class="picture-display">
                
                <img src="{{ url_for('static', filename = 'images/profile_pic/' + post.author.prof_pic) }}" alt="">
            </div>
        </div>
    {% endfor %}
   
</div>





{% endblock Body %}

{% block more %}
    <div class="after-post">
        {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 2, right_current = 3) %}
            {% if page_num %}
                {% if page_num == posts.page %}
                    <a class="btn-info solid" href="{{ url_for('users.User_Posts', username = user.username, page = page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn-info" href="{{ url_for('users.User_Posts', username = user.username,  page = page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}

        {% endfor %}
    </div>

    

{% endblock more %}